Description: >
  Isaac Gutierrez
  Setup IAM roles and users

Resources:

  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: Json
      Description: String
      ManagedPolicyArns:
        - String
      MaxSessionDuration: Integer
      Path: String
      PermissionsBoundary: String
      Policies:
        - Policy
      RoleName: String
      Tags:
        - Tag
