Description: >
    Isaac Gutierrez
    Creates bucket to host app deployments
Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

Resources:

  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: lab02apprep

Outputs:

  DeployBucket:
    Description: Bucket ID where to find deployment files
    Value: !Ref S3Bucket
    Export:
      Name: !Sub ${EnvironmentName}-BUCKETID
